[ADD] SSD 테스트 코드 및 Read, Write 기능 구현
ghkdwlscks/ssd pull request #7
Opened 2024-07-15 07:59 UTC by GeunpyoKang

2024-07-15 23:37 UTC, ghkdwlscks requested changes

2024-07-15 23:37 UTC, ghkdwlscks commented on test/test_ssd.py
> +NAND_FILE = '../output/nand.txt'
직접 File 사용하는 대신 Mock을 사용해야 할 것 같아요

2024-07-15 23:47 UTC, ghkdwlscks requested changes

2024-07-15 23:47 UTC, ghkdwlscks commented on ssd.py
> +            raise AttributeError
이 부분 `if __name__ == "main"`에서 catch해서 pass 해야 RuntimeError 안날 것 같아요

2024-07-15 23:53 UTC, ghkdwlscks commented on ssd.py
> +    data = args[3]
![image](https://github.com/user-attachments/assets/fafaad4e-8b2a-45b2-bd90-dc23ff6528cc)
PR 땡겨서 테스트 했을 때 Read에서 에러나서 len(args) 검사해줘야할 것 같아요

2024-07-15 23:59 UTC, SUMIN97 requested changes

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +CMD_LIST = ['R', 'W']
FR도 추가 부탁드립니다ㅎㅎ

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +                    if int(lba) == self.lba:
lba 가 string인지 int인지에 따라 따로 변수를 만들어 주시면 좋을 것 같습니다!

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +    def read(self):
교안에 
"R명령어 사용시 nand.txt 파일 내용 전체 읽어온 후 필요한 부분을 찾아내어 Return 한다"
라고 되어 있는데 중간에 while문을 break 해도 될까요?

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +        except:
파일이 없으면 invalid error가 나야 하는건 아닐까요??

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +        if self.lba < len(lines):
self.lba >= len(lines)일때 invalid error가 나야할 것 같습니다.

2024-07-15 23:59 UTC, SUMIN97 commented on ssd.py
> +    def write(self):
nand.txt 에 어떤 형식으로 저장되는지  주석으로 앞에 적어주시면 test할때 도움이 될 것 같습니다~

2024-07-16 00:04 UTC, hyowon-moon requested changes

2024-07-16 00:04 UTC, hyowon-moon commented on ssd.py
> +        print(f'{self.lba} read')
ssd.py는 "화면 출력하지 않고, result.txt 파일에 결과를 저장" 이라고 교안에 돼 있어서 print 부분은 지워도 될 것 같습니다.

2024-07-16 00:05 UTC, ghkdwlscks commented on ssd.py
> +        print(f'{self.lba} read')
실제 동작시에는 필요없을 것 같습니다

2024-07-16 00:06 UTC, Nakru requested changes

2024-07-16 00:06 UTC, Nakru commented on ssd.py
> +        if cmd not in CMD_LIST:
validation 부분은 함수로 변경하여 가독성을 올리는 것도 좋을 것 같습니다!

2024-07-16 00:06 UTC, Nakru commented on ssd.py
> +            with open(self.nand_file_path, 'w') as file:
파일 open 후 alias를 통일 하면 좋을 것 같습니다. f 혹은 file로 통일해야 추후 검색을 통한 수정을 할 때 일관성 있게 수정가능할 것 같습니다.

2024-07-16 00:11 UTC, ghkdwlscks commented
`nand.txt`의 내용이 비어있을 때 아무것도 나오는 것이 없습니다 (Read/Write에서 찾지 못해서 아무것도 못합니다)
일단은 코드 수정 대신 nand.txt 안에 default 값들 적어놓은 commit 하나 추가해주시면 될 것 같아요


(`refresh_nand()`가 만약 이런 역할을 기대한거라면 지워도 될 것 같습니다)

2024-07-16 00:52 UTC, GeunpyoKang commented on test/test_ssd.py
> +NAND_FILE = '../output/nand.txt'
done

2024-07-16 00:56 UTC, GeunpyoKang commented on ssd.py
> +            raise AttributeError
`__main__` 부분이 어떤 값으로 넘어올지는 사실 ssd 입장에서는 모르는 것이어서 좀 더 validation check할 필요가 있어 보입니다. 해당 부분은 좀 더 고민해보고 추가할 수 있도록 하겠습니다. 현재는 `subprocess.run`으로 들어오는 인수의 길이에 따라 lba를 잘 넣어주고 int 처리하는 것을 적용하였습니다.

2024-07-16 00:56 UTC, GeunpyoKang commented on ssd.py
> +    data = args[3]
done

2024-07-16 00:57 UTC, GeunpyoKang commented on ssd.py
> +                    if int(lba) == self.lba:
lba가 들어올 때 `int`로만 들어오게 수정하였습다. done

2024-07-16 00:57 UTC, GeunpyoKang commented on ssd.py
> +    def read(self):
해당 부분 수정하여 반영하였습니다. done

2024-07-16 00:57 UTC, GeunpyoKang commented on ssd.py
> +        except:
파일이 없으면, 초기화 하는 로직으로 추가하였습니다! done

2024-07-16 00:58 UTC, GeunpyoKang commented on ssd.py
> +        if self.lba < len(lines):
error 발생 가드절 추가하였습니다. done

2024-07-16 00:58 UTC, GeunpyoKang commented on ssd.py
> +    def write(self):
done

2024-07-16 00:58 UTC, GeunpyoKang commented on ssd.py
> +        print(f'{self.lba} read')
미처 삭제하지 못했군요! 삭제했습니다. done

2024-07-16 00:58 UTC, GeunpyoKang commented on ssd.py
> +        print(f'{self.lba} read')
done

2024-07-16 01:00 UTC, GeunpyoKang commented on ssd.py
> +        if cmd not in CMD_LIST:
cmd 부분은 해당 코드로도 명확해보여서 일단 이렇게 처리하였는데, `cmd_list`와 같은 경우는 한 군데에서 관리하면 좋을 것 같아서 같이 이야기해보고 정해보시죠! 그 후 밸리데이션 체크에 대한 함수 구현해보겠습니다!

2024-07-16 01:00 UTC, GeunpyoKang commented on ssd.py
> +            with open(self.nand_file_path, 'w') as file:
좋은 의견입니다. `f`로 통일하였습니다. done

2024-07-16 01:04 UTC, hyowon-moon approved these changes

2024-07-16 01:07 UTC, Nakru approved these changes

2024-07-16 01:10 UTC, ghkdwlscks commented on ssd.py
> +            raise AttributeError
에러나서 프로그램 죽으면 안된다고 했긴 했는데 ssd.py가 죽는거라 shell에는 상관없을 것 같기도 하네요

2024-07-16 01:12 UTC, SUMIN97 approved these changes

2024-07-16 01:14 UTC, ghkdwlscks approved these changes

2024-07-16 01:19 UTC, merged